import type { ProviderCategories } from '@/types/categories';

export const AAM_CATEGORIES: ProviderCategories = {
  hitInfo: {
    label: 'Hit Info',
    icon: '📊',
    order: 1,
    defaultExpanded: true,
    patterns: [/^Request Type$/, /^Account$/],
  },
  general: {
    label: 'General',
    icon: '🔧',
    order: 2,
    defaultExpanded: true,
    patterns: [
      /^Caller$/,
      /^Callback Property$/,
      /^Data Provider/,
      /^Integration Code/,
      /^COPPA/,
      /^Return Traits/,
      /^Data Provider ID$/,
      /^Data Provider User ID$/,
      /^Return URL/,
      /^Adobe Analytics Integration$/,
      /^JSON Response$/,
      /^Experience Cloud ID/,
      /^Name Space ID$/,
      /^Platform$/,
      /^Legacy AA/,
      /^Return Method$/,
      /^Score ID$/,
      /^Trait Source/,
      /^Unique User ID$/,
      /^Org ID/,
      /^Blob$/,
      /^Version$/,
      /^DCS Region$/,
      /^Redirect$/,
      /^GDPR$/,
      /^Consent String$/,
    ],
  },
  customer: {
    label: 'Customer Attributes',
    icon: '👥',
    order: 3,
    defaultExpanded: true,
    prefixMatch: ['c_'],
    patterns: [],
  },
  private: {
    label: 'Private Attributes',
    icon: '🔒',
    order: 4,
    defaultExpanded: false,
    prefixMatch: ['p_'],
    patterns: [],
  },
};
