import type { ProviderCategories } from '@/types/categories';

export const ANALYTICS_CLIENT_CATEGORIES: ProviderCategories = {
  hit: {
    label: 'Hit Info',
    icon: '📊',
    order: 1,
    defaultExpanded: true,
    patterns: [
      /^Hit type$/,
      /^Page name$/,
      /^Page URL$/,
      /^Referrer$/,
      /^Link name$/,
      /^Link URL$/,
      /^Report suite$/,
    ],
  },
  tracking: {
    label: 'Report Suite & Tracking',
    icon: '🔑',
    order: 2,
    defaultExpanded: true,
    patterns: [
      /^Channel$/,
      /^Server$/,
      /^AppMeasurement$/,
      /^Resolution$/,
      /^Color depth$/,
      /^JavaScript ver$/,
    ],
  },
  events: {
    label: 'Events',
    icon: '⚡',
    order: 3,
    defaultExpanded: true,
    patterns: [/^Events$/, /^events?$/, /^ev$/],
    specialRenderer: 'adobeEvents',
  },
  eVars: {
    label: 'eVars',
    icon: '🔢',
    order: 4,
    defaultExpanded: true,
    patterns: [/^eVar\d+$/],
  },
  props: {
    label: 'Props',
    icon: '📌',
    order: 5,
    defaultExpanded: true,
    patterns: [/^prop\d+$/],
  },
  products: {
    label: 'Products',
    icon: '🛍️',
    order: 6,
    defaultExpanded: true,
    patterns: [/^Products$/, /^products?$/, /^pl$/],
    specialRenderer: 'adobeProducts',
  },
  listVars: {
    label: 'List Variables',
    icon: '📋',
    order: 7,
    defaultExpanded: false,
    patterns: [/^list\d+$/],
  },
  contextData: {
    label: 'Context Data',
    icon: '🏷️',
    order: 8,
    defaultExpanded: true,
    patterns: [/^Context data$/],
  },
  identity: {
    label: 'Identity',
    icon: '👤',
    order: 9,
    defaultExpanded: true,
    patterns: [/^Visitor ID$/, /^mid$/, /^aid$/, /^fid$/],
  },
  campaignAttrib: {
    label: 'Campaign & Attribution',
    icon: '🎯',
    order: 10,
    defaultExpanded: true,
    patterns: [/^Campaign$/, /^v0$/],
  },
};
