import type { ProviderCategories } from '@/types/categories';

export const GA4_CATEGORIES: ProviderCategories = {
  hit: {
    label: 'Hit Info',
    icon: '📊',
    order: 1,
    defaultExpanded: true,
    patterns: [
      /^en$/,
      /^Event$/,
      /^_et$/,
      /^Engagement$/,
      /^_s$/,
      /^Hit Sequence$/,
      /^_ss$/,
      /^_fv$/,
      /^_nsi$/,
      /^_ee$/,
      /^seg$/,
      /^Session Engaged$/,
      /^sid$/,
      /^Session ID$/,
      /^sct$/,
      /^Session Count$/,
    ],
  },
  measurement: {
    label: 'Measurement',
    icon: '🔑',
    order: 2,
    defaultExpanded: true,
    patterns: [
      /^tid$/,
      /^Measurement ID$/,
      /^v$/,
      /^_p$/,
      /^gtm$/,
      /^GTM Version$/,
      /^_gid$/,
      /^_dbg$/,
    ],
  },
  page: {
    label: 'Page & Content',
    icon: '📄',
    order: 3,
    defaultExpanded: true,
    patterns: [
      /^dl$/,
      /^dp$/,
      /^dr$/,
      /^dt$/,
      /^Page$/,
      /^Page title$/,
      /^Referrer$/,
      /^page_location$/,
      /^page_title$/,
      /^page_referrer$/,
      /^page_path$/,
    ],
    prefixMatch: ['cg'],
  },
  eventData: {
    label: 'Event Parameters',
    icon: '⚡',
    order: 4,
    defaultExpanded: true,
    patterns: [],
    prefixMatch: ['ep.', 'epn.'],
  },
  user: {
    label: 'User & Session',
    icon: '👤',
    order: 5,
    defaultExpanded: true,
    patterns: [
      /^cid$/,
      /^uid$/,
      /^user_id$/,
      /^client_id$/,
      /^Client ID$/,
      /^User ID$/,
      /^ECID$/,
      /^_ga$/,
    ],
    prefixMatch: ['up.', 'upn.'],
    requiredParams: ['cid', 'client_id', 'Client ID', 'User ID'],
  },
  campaign: {
    label: 'Campaign',
    icon: '🎯',
    order: 6,
    defaultExpanded: true,
    patterns: [/^gclid$/, /^dclid$/, /^gbraid$/, /^wbraid$/, /^srsltid$/],
    prefixMatch: ['utm_'],
  },
  ecommerce: {
    label: 'Ecommerce',
    icon: '🛒',
    order: 7,
    defaultExpanded: true,
    patterns: [
      /^transaction_id$/,
      /^value$/,
      /^currency$/,
      /^Currency$/,
      /^cu$/,
      /^items$/,
      /^tax$/,
      /^shipping$/,
      /^pa$/,
      /^tcc$/,
    ],
    prefixMatch: ['pr'],
  },
  consent: {
    label: 'Consent & Privacy',
    icon: '🔒',
    order: 8,
    defaultExpanded: false,
    patterns: [
      /^gcs$/,
      /^Consent State$/,
      /^gcd$/,
      /^Consent Defaults$/,
      /^npa$/,
      /^Non-personalized Ads$/,
      /^dma$/,
      /^DMA Compliance$/,
      /^dma_cps$/,
      /^DMA Consent$/,
      /^gdpr$/,
      /^gdpr_consent$/,
    ],
  },
  device: {
    label: 'Device & Browser',
    icon: '💻',
    order: 9,
    defaultExpanded: false,
    patterns: [
      /^sr$/,
      /^Screen Resolution$/,
      /^vp$/,
      /^sd$/,
      /^de$/,
      /^ul$/,
      /^User Language$/,
      /^je$/,
    ],
  },
};
