import type { ProviderCategories } from '@/types/categories';

export const CLARITY_CATEGORIES: ProviderCategories = {
  envelope: {
    label: 'Envelope',
    icon: '📦',
    order: 1,
    defaultExpanded: true,
    patterns: [
      /^Version$/,
      /^Project ID$/,
      /^User ID$/,
      /^Session ID$/,
      /^Page Number$/,
      /^Sequence$/,
      /^Duration/,
      /^Upload Type$/,
      /^Is Last Payload$/,
      /^Platform$/,
      /^Request Type$/,
    ],
    prefixMatch: ['Page URL'],
  },
  summary: {
    label: 'Summary',
    icon: '📊',
    order: 2,
    defaultExpanded: true,
    patterns: [/^Event Count$/, /^Event Types$/],
  },
  interaction: {
    label: 'Interaction',
    icon: '👆',
    order: 3,
    defaultExpanded: true,
    patterns: [
      /^Click/,
      /^Scroll/,
      /^DoubleClick/,
      /^Resize/,
      /^Mouse/,
      /^Touch/,
      /^Selection/,
      /^Clipboard/,
      /^Form Submit/,
      /^Input/,
      /^Focus/,
      /^Context Menu/,
    ],
  },
  custom: {
    label: 'Custom Events',
    icon: '⚡',
    order: 4,
    defaultExpanded: true,
    patterns: [/^Custom Event/],
  },
  page: {
    label: 'Page & Navigation',
    icon: '📄',
    order: 5,
    defaultExpanded: true,
    patterns: [/^Page \[/, /^Navigation/, /^Visibility/, /^Unload/],
  },
  consent: {
    label: 'Consent',
    icon: '🔒',
    order: 6,
    defaultExpanded: true,
    patterns: [/^Consent/],
  },
  dimensions: {
    label: 'Dimensions',
    icon: '📐',
    order: 7,
    defaultExpanded: false,
    patterns: [/^Dim:/],
  },
  metrics: {
    label: 'Metrics',
    icon: '📊',
    order: 8,
    defaultExpanded: false,
    patterns: [/^Metric:/],
  },
  variables: {
    label: 'Variables',
    icon: '🏷️',
    order: 9,
    defaultExpanded: false,
    patterns: [/^Variable:/],
  },
  heartbeat: {
    label: 'Heartbeat',
    icon: '💓',
    order: 10,
    defaultExpanded: false,
    patterns: [/^Ping/],
  },
  internal: {
    label: 'Internal',
    icon: '⚙️',
    order: 11,
    defaultExpanded: false,
    patterns: [
      /^Upload \[/,
      /^Upgrade/,
      /^Baseline/,
      /^Limit/,
      /^Log/,
      /^ScriptError/,
      /^Change/,
      /^Timeline/,
      /^Summary/,
    ],
  },
};
