import type { ProviderCategories } from '@/types/categories';

export const PIXEL_CATEGORIES: ProviderCategories = {
  event: {
    label: 'Event',
    icon: '⚡',
    order: 1,
    defaultExpanded: true,
    patterns: [
      /^ev$/,
      /^Event$/,
      /^a$/,
      /^Action$/,
      /^eid$/,
      /^Event ID$/,
      /^ec$/,
      /^Event Count$/,
      /^o$/,
      /^Ordinal$/,
      /^ler$/,
      /^Last Event Result$/,
    ],
  },
  pixel: {
    label: 'Pixel Info',
    icon: '🔑',
    order: 2,
    defaultExpanded: true,
    patterns: [/^id$/, /^Pixel ID$/, /^v$/, /^Pixel Version$/, /^r$/, /^Release$/],
  },
  page: {
    label: 'Page',
    icon: '📄',
    order: 3,
    defaultExpanded: true,
    patterns: [/^dl$/, /^URL$/, /^rl$/, /^Referrer$/],
  },
  ecommerce: {
    label: 'Ecommerce',
    icon: '🛒',
    order: 4,
    defaultExpanded: true,
    patterns: [
      /^Value$/,
      /^Currency$/,
      /^Content IDs$/,
      /^Content Name$/,
      /^Content Type$/,
      /^Content Category$/,
      /^Num Items$/,
      /^Contents$/,
    ],
  },
  tracking: {
    label: 'Tracking',
    icon: '🍪',
    order: 5,
    defaultExpanded: true,
    patterns: [/^fbp$/, /^FBP$/, /^fbc$/, /^FBC$/],
  },
  device: {
    label: 'Device',
    icon: '💻',
    order: 6,
    defaultExpanded: false,
    patterns: [/^Screen Resolution$/],
  },
  technical: {
    label: 'Technical',
    icon: '⚙️',
    order: 7,
    defaultExpanded: false,
    patterns: [
      /^ts$/,
      /^Timestamp$/,
      /^plt$/,
      /^Page Load Time$/,
      /^if$/,
      /^In iFrame$/,
      /^cdl$/,
      /^Consent Data Layer$/,
      /^cf$/,
      /^Consent Flag$/,
      /^it$/,
      /^Init Time$/,
      /^coo$/,
      /^Click-Only$/,
      /^Experiments$/,
    ],
  },
};
